/*
 * ColorOSNotifyIcon - Optimize notification icons for ColorOS and adapt to native notification icon specifications.
 * Copyright (C) 20174 Fankes Studio(qzmmcn@163.com)
 * Copyright (C) 2026 YisRime
 *
 * https://github.com/fankes/ColorOSNotifyIcon
 *
 * This software is non-free but opensource software: you can redistribute it
 * and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation; either
 * version 3 of the License, or any later version.
 * <p>
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * and eula along with this software.  If not, see
 * <https://www.gnu.org/licenses/>
 *
 * This file is created by fankes on 2022/2/8.
 */
package de.yisrime.cosicon.utils.tool

import android.content.Context
import android.os.Build
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import de.yisrime.cosicon.const.PackageName
import de.yisrime.cosicon.data.ConfigData
import de.yisrime.cosicon.ui.activity.MainActivity
import de.yisrime.cosicon.utils.factory.colorOSFullVersion
import de.yisrime.cosicon.utils.factory.delayedRun
import de.yisrime.cosicon.utils.factory.execShell
import de.yisrime.cosicon.utils.factory.showDialog
import de.yisrime.cosicon.utils.factory.snake
import com.google.android.material.snackbar.Snackbar
import de.yisrime.cosicon.wrapper.FrameworkWrapper
import de.yisrime.cosicon.utils.tool.ModuleLog
import de.yisrime.cosicon.wrapper.BuildConfigWrapper
import java.util.Locale

/**
 * 系统界面工具
 */
object SystemUITool {

    /** 待导出的日志内容 */
    private var pendingExportContent: String? = null

    /** 当前启动器实例 */
    private var launcher: ActivityResultLauncher<String>? = null

    /**
     * 宿主注册监听
     */
    object Host {

        /**
         * 监听系统界面刷新改变
         * @param result 回调 - ([Boolean] 是否成功)
         */
        fun onRefreshSystemUI(result: (Boolean) -> Boolean) {
            HostBridge.hostRegisterCacheHandler(result)
        }

        /**
         * 监听通知图标数据刷新请求
         * @param refresh 接收模块的仓库版本与异步刷新回调
         */
        fun onRefreshIconData(refresh: (Pair<String, Long>, (Boolean) -> Unit) -> Unit) {
            HostBridge.hostRegisterIconDataHandler(refresh)
        }
    }

    /**
     * 检查模块是否激活
     * @param context 实例
     * @param result 成功后回调
     */
    fun checkingActivated(context: Context, result: (Boolean) -> Unit) =
        HostBridge.request(context, HostBridge.KIND_QUERY_VERSION) { intent ->
            result(intent.getIntExtra(HostBridge.EXTRA_VERSION_CODE, 0) == BuildConfigWrapper.VERSION_CODE)
        }

    /**
     * 注册导出调试日志启动器到 [AppCompatActivity]
     * @param activity 实例
     */
    fun registerExportDebugLogsLauncher(activity: AppCompatActivity) {
        launcher = activity.registerForActivityResult(ActivityResultContracts.CreateDocument("*/application")) { result ->
            runCatching {
                result?.let { e ->
                    val content = "" +
                        "================================================================\n" +
                        "    Generated by ColorOSNotifyIcon\n" +
                        "    Project Url: https://github.com/fankes/ColorOSNotifyIcon\n" +
                        "================================================================\n\n" +
                        "[Device Brand]: ${Build.BRAND}\n" +
                        "[Device Model]: ${Build.MODEL}\n" +
                        "[Display]: ${Build.DISPLAY}\n" +
                        "[Android Version]: ${Build.VERSION.RELEASE}\n" +
                        "[Android API Level]: ${Build.VERSION.SDK_INT}\n" +
                        "[ColorOS Version]: $colorOSFullVersion\n" +
                        "[System Locale]: ${Locale.getDefault()}\n\n" + (pendingExportContent ?: "").trim()
                    activity.contentResolver?.openOutputStream(e)?.apply { write(content.toByteArray()) }?.close()
                    activity.snake(msg = "导出完成")
                } ?: activity.snake(msg = "已取消操作")
            }.onFailure { activity.snake(msg = "导出过程发生错误") }
        }
    }

    /**
     * 获取并导出全部调试日志
     * @param context 实例
     */
    fun obtainAndExportDebugLogs(context: Context) {
        /** 执行导出操作 */
        fun doExport() = HostBridge.request(context, HostBridge.KIND_DUMP_LOGS) { intent ->
            pendingExportContent = HostBridge.readHostLogs(intent.getStringExtra(HostBridge.EXTRA_LOG_NAME))
            val content = pendingExportContent
            if (content.isNullOrEmpty()) context.snake(msg = "暂无调试日志")
            else runCatching { launcher?.launch("coloros_notification_icons_processing_logs.log") }
                .onFailure { context.snake(msg = "启动系统文件选择器失败") }
        }
        if (FrameworkWrapper.isBound) doExport()
        else context.snake(msg = "模块没有激活，请先激活模块")
    }

    /**
     * 重启系统界面
     * @param context 实例
     */
    fun restartSystemUI(context: Context) {
        /** 动态刷新功能是否可用 */
        val isDynamicAvailable = ConfigData.isEnableModule && MainActivity.isModuleRegular && MainActivity.isModuleValied

        /** 当 Root 权限获取失败时显示对话框 */
        fun showWhenAccessRootFail() =
            context.showDialog {
                title = "获取 Root 权限失败"
                msg = "当前无法获取 Root 权限，请确认你的设备已经被 Root 且同意授予 Root 权限。\n" +
                    "如果你正在使用 Magisk 并安装了 Shamiko 模块，" +
                    "请确认当前是否正处于白名单模式。 (白名单模式将导致无法申请 Root 权限)"
                confirmButton(text = "我知道了")
            }
        context.showDialog {
            title = "重启系统界面"
            msg = "你确定要立即重启系统界面吗？\n\n" +
                "重启过程会黑屏并等待进入锁屏重新解锁。" + (if (isDynamicAvailable)
                    "\n\n你也可以选择“立即生效”来动态刷新系统界面并生效当前模块设置。" else "")
            confirmButton {
                execShell(cmd = "pgrep systemui").also { pid ->
                    if (pid.isNotBlank())
                        execShell(cmd = "kill -9 $pid")
                    else showWhenAccessRootFail()
                }
            }
            cancelButton()
            if (isDynamicAvailable) neutralButton(text = "立即生效") { refreshSystemUI(context) }
        }
    }

    /**
     * 刷新系统界面状态栏与通知图标
     * @param context 实例
     * @param isRefreshCacheOnly 仅刷新缓存不刷新图标和通知改变 - 默认：否
     * @param isRefreshIconData 是否刷新通知图标数据 - 默认：否
     * @param callback 成功后回调
     */
    fun refreshSystemUI(
        context: Context? = null,
        isRefreshCacheOnly: Boolean = false,
        isRefreshIconData: Boolean = false,
        callback: () -> Unit = {}
    ) {
        /**
         * 刷新系统界面
         * @param result 回调结果
         */
        fun doRefresh(result: (Boolean) -> Unit) {
            val target = context ?: run {
                result(false)
                return
            }
            if (isRefreshIconData) {
                HostBridge.request(
                    target,
                    HostBridge.KIND_REFRESH_ICON_DATA,
                    repoVersion = IconRuleManagerTool.snapshotVersion ?: ("" to 0L)
                ) { intent -> result(intent.getBooleanExtra(HostBridge.EXTRA_RESULT, false)) }
            } else {
                HostBridge.request(target, HostBridge.KIND_REFRESH_CACHE, booleanPayload = isRefreshCacheOnly) { intent ->
                    result(intent.getBooleanExtra(HostBridge.EXTRA_RESULT, false))
                }
            }
        }
        when {
            FrameworkWrapper.isBound && context is AppCompatActivity ->
                context.showDialog {
                    title = "请稍后"
                    progressContent = "正在等待系统界面刷新"
                    /** 是否等待成功 */
                    var isWaited = false
                    /** 设置等待延迟 */
                    delayedRun(ms = 5000) {
                        if (isWaited) return@delayedRun
                        cancel()
                        context.snake(msg = "预计响应超时，建议重启系统界面", actionText = "立即重启") { restartSystemUI(context) }
                    }
                    checkingActivated(context) { isValied ->
                        when {
                            isValied.not() -> {
                                cancel()
                                isWaited = true
                                context.snake(msg = "请重启系统界面以生效模块更新", actionText = "立即重启") { restartSystemUI(context) }
                            }
                            else -> doRefresh {
                                cancel()
                                isWaited = true
                                if (it) callback()
                                if (it.not()) context.snake(msg = "刷新失败，建议重启系统界面", actionText = "立即重启") { restartSystemUI(context) }
                            }
                        }
                    }
                    noCancelable()
                }
            FrameworkWrapper.isBound.not() && context is AppCompatActivity -> context.snake(msg = "模块没有激活，更改不会生效")
            else -> doRefresh { if (it) callback() }
        }
    }

    /**
     * 显示需要重启系统界面的 [Snackbar]
     * @param context 实例
     */
    fun showNeedRestartSnake(context: Context) =
        if (FrameworkWrapper.isBound)
            context.snake(msg = "设置需要重启系统界面才能生效", actionText = "立即重启") { restartSystemUI(context) }
        else context.snake(msg = "模块没有激活，更改不会生效")
}
